<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="arm">
  <!-- Simple, conservative placeholder geometry for visualization and TF -->
  <xacro:property name="shoulder_length" value="0.12"/>
  <xacro:property name="upper_arm_length" value="0.20"/>
  <xacro:property name="forearm_length" value="0.20"/>
  <xacro:property name="wrist_length" value="0.10"/>
  <xacro:property name="radius" value="0.025"/>

  <material name="dark_grey">
    <color rgba="0.2 0.2 0.2 1.0"/>
  </material>
  <material name="light_grey">
    <color rgba="0.7 0.7 0.7 1.0"/>
  </material>

  <link name="base_link">
    <visual>
      <geometry>
        <cylinder length="0.05" radius="0.06"/>
      </geometry>
      <material name="dark_grey"/>
    </visual>
  </link>

  <joint name="shoulder_pitch" type="revolute">
    <parent link="base_link"/>
    <child link="shoulder_pitch_link"/>
    <origin xyz="0 0 0.05" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="20.0" velocity="1.5" lower="-1.57" upper="1.57"/>
  </joint>

  <link name="shoulder_pitch_link">
    <visual>
      <origin xyz="0 0 ${shoulder_length/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${shoulder_length}" radius="${radius}"/>
      </geometry>
      <material name="light_grey"/>
    </visual>
  </link>

  <joint name="shoulder_yaw" type="revolute">
    <parent link="shoulder_pitch_link"/>
    <child link="shoulder_yaw_link"/>
    <origin xyz="0 0 ${shoulder_length}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="20.0" velocity="1.5" lower="-1.57" upper="1.57"/>
  </joint>

  <link name="shoulder_yaw_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.05" radius="${radius}"/>
      </geometry>
      <material name="dark_grey"/>
    </visual>
  </link>

  <joint name="shoulder_roll" type="revolute">
    <parent link="shoulder_yaw_link"/>
    <child link="shoulder_roll_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit effort="20.0" velocity="1.5" lower="-1.57" upper="1.57"/>
  </joint>

  <link name="shoulder_roll_link">
    <visual>
      <origin xyz="0 0 ${upper_arm_length/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${upper_arm_length}" radius="${radius}"/>
      </geometry>
      <material name="light_grey"/>
    </visual>
  </link>

  <joint name="elbow_flex" type="revolute">
    <parent link="shoulder_roll_link"/>
    <child link="elbow_link"/>
    <origin xyz="0 0 ${upper_arm_length}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="15.0" velocity="1.5" lower="-2.35" upper="0.52"/>
  </joint>

  <link name="elbow_link">
    <visual>
      <origin xyz="0 0 ${forearm_length/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${forearm_length}" radius="${radius}"/>
      </geometry>
      <material name="dark_grey"/>
    </visual>
  </link>

  <joint name="wrist_pitch" type="revolute">
    <parent link="elbow_link"/>
    <child link="wrist_pitch_link"/>
    <origin xyz="0 0 ${forearm_length}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="10.0" velocity="1.5" lower="-1.57" upper="1.57"/>
  </joint>

  <link name="wrist_pitch_link">
    <visual>
      <origin xyz="0 0 ${wrist_length/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${wrist_length}" radius="${radius}"/>
      </geometry>
      <material name="light_grey"/>
    </visual>
  </link>

  <joint name="wrist_roll" type="revolute">
    <parent link="wrist_pitch_link"/>
    <child link="wrist_roll_link"/>
    <origin xyz="0 0 ${wrist_length}" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit effort="10.0" velocity="1.5" lower="-3.14" upper="3.14"/>
  </joint>

  <link name="wrist_roll_link">
    <visual>
      <origin xyz="0 0 0.05" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.1" radius="${radius}"/>
      </geometry>
      <material name="dark_grey"/>
    </visual>
  </link>

  <joint name="tool0_fixed" type="fixed">
    <parent link="wrist_roll_link"/>
    <child link="tool0"/>
    <origin xyz="0 0 0.1" rpy="0 0 0"/>
  </joint>

  <link name="tool0">
    <visual>
      <geometry>
        <box size="0.03 0.03 0.03"/>
      </geometry>
      <material name="light_grey"/>
    </visual>
  </link>
</robot>
